version: '3'
services:
    redis:
        image: redis
        ports:
            - ${REDIS_PORT}:6379
        volumes:
            - 'redisdata:/data'
    db:
        image: postgres
        ports:
            - ${DB_PORT}:5432
        environment:
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - 'pgdata:/var/lib/postgresql/data/'
    api:
        build: './'
        depends_on:
            - db
            - redis
        ports:
            - ${API_PORT}:4000
        env_file:
            - ./.env
        command: ['./wait-for-it.sh', 'db:5432', '--', 'node', 'index.js']
volumes:
    pgdata:
    redisdata:
